### ISSUE TITLE
DCE regex is not strict enough

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/node-api#44]
See rit-sse/scoreboard-2.0#41

**Comment by billdybas** [comment]
See https://github.com/rit-sse/node-api/blob/master/models/user.js#L14

**Comment by 7imbrook** [comment]
**PLAN**: attempt email to dce@rit.edu, if doesn't bounce then 👍 
_actual_: to lower the model `isLowercase: true`
or
```
/* a setter for 'title' property */
function(title) {
    return this.setDataValue('title', title.toString().toLowerCase());
}
```

**Comment by 7imbrook** [comment]
I'm going to fix the issue on the db side, merge that data

**Comment by kristenmills** [comment]
I think just fixing the line @billdybas posted will do the trick

**Comment by 7imbrook** [comment]
wont fix whats been stored

**Comment by kristenmills** [comment]
I know. I was talking about for the future.

**Comment by kristenmills** [comment]
I'm going to make that change.  Right now.

**Comment by kristenmills** [comment]
Fixed it.

**Comment by 7imbrook** [comment]
the issue in the db was with a space after the dce, can you also change the var char size to 7?

**Comment by 7imbrook** [comment]
the space is a tab character.......

**Comment by 7imbrook** [comment]
db issue resolved.

**Comment by kristenmills** [comment]
There are still 3 michael timbrooks lol

**Comment by kristenmills** [comment]
#45 pull request to change the var char. I think this will break until you finish fixing the DB so merge it after.

**Comment by 7imbrook** [comment]
the db, is fixed.

**Comment by kristenmills** [comment]
I don't believe you.

**Comment by kristenmills** [comment]
![screen shot 2016-11-04 at 10 08 12 am](https://cloud.githubusercontent.com/assets/1054558/20015005/b1ee9154-a276-11e6-835b-228f8693e9e5.png)

**Comment by kristenmills** [comment]
@7imbrook any update on this?

**Comment by 7imbrook** [comment]
I fixe the data in the db, but I didn't fix the problem. Someone's adding tab characters to the end. The input needs to be validated. @kristenmills

**Comment by 7imbrook** [comment]
I alter tabled to have a max length of 7 for memberships and user dce. Sweetman was another violator. Whitespace chars have been getting added to the end.

**Comment by kristenmills** [comment]
Yeah the model validations have already been updated (https://github.com/rit-sse/node-api/commit/72c9160dc8afbff341574a75c5ec81875c6cda27). If the 2 extra timbrooks and extra sweetman is gone, and table is altered, I vote we close this.

**Comment by 7imbrook** [comment]
Agreed
