### ISSUE TITLE
Error when updating officer end date

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/node-api#49]
When I try to update an officer's end date, I get the following error:

<img width="848" alt="screen shot 2017-05-10 at 6 01 16 pm" src="https://cloud.githubusercontent.com/assets/7254185/25923283/b5a9a65e-35aa-11e7-8d89-94953548b118.png">

**Comment by 7imbrook** [comment]
@kristenmills wanna triage this one?

**Comment by wadeanthony0100** [comment]
Not sure if anyone did anything for this, but the update feature is working now. Motion to close? @7imbrook

**Comment by kristenmills** [comment]
I didn't do anything. Probably close for now...Reopen if it happens again.

**Comment by kristenmills** [comment]
Found actual root cause for this.  It's a one repo bug, fixing shortly.
