### ISSUE TITLE
Entry point. 

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/node-api#56]
I was looking through the apiary docs and apparently I described an entrypoint endpoint 
http://docs.sse.apiary.io/#reference/sse-api-root/retrieve-the-entry-point/retrieve-the-entry-point

Not a terrible idea.

**Comment by kristenmills** [comment]
@7imbrook @billdybas @vuzDylan Thoughts? I don't think I would do it exactly as described in the apiary docs.  I would think something of the sort would live at `/` `/mentoring` and `/qdb` though.

**Comment by 7imbrook** [comment]
yeah, I really don't like root 404ing. I can get behind this.
