### ISSUE TITLE
Scoreboard: Send Congrats Email on First Membership

### ISSUE THREAD

**Issue by billdybas** [rit-sse/node-api#62]
We talked about sending an email to people when they get their first membership of the semester congratulating them and explaining what membership gives them.

[Mailgun has 10K free emails a month](https://www.mailgun.com/pricing) which seems like a viable option. 

Acceptance Criteria:
- Integrate w/ Mailgun
- Create email template w/ body copy
- Send the email to users if this is the first membership they are given this semester

**Comment by billdybas** [comment]
@robmcl4 Please put together and email me the body copy you'd like to be in the email.

**Comment by robmcl4** [comment]
```
Subject: You've earned SSE Membership!
Body:
Hello <FirstName>,

Congratulations! You have earned your first SSE membership for this semester. Thank you for contributing to the organization, we greatly appreciate your support.

You now have access to exclusive discounted pricing on select SSE events, as well as voting rights in the Primary Officer's election.

Thanks for being awesome!
<Secretary Name>,
Secretary, Society of Software Engineers
```

**Comment by wadeanthony0100** [comment]
Were we planning on sending this out in plain text, or in a styled page format?
Should we consult branding on styles? Or at least add the SSE logo to the bottom? 
![SSE Logo](https://github.com/rit-sse/branding/blob/master/images/big-logo.png?raw=true)

**Comment by billdybas** [comment]
I was planning on making a styled HTML email. I can include our logo and branding. 

When I'm working on this, I'll make a WIP PR and add screenshots to it, so we can talk about and agree on a final design.
